{{- if .Values.rollouts.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-config-hook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: rollout-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-config-hook
subjects:
- kind: ServiceAccount
  name: rollout-config-hook
  namespace: {{ .Release.Namespace }}
{{- end }}
