{{- if .Values.rollouts.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-config-hook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: rollout-config
{{- end }}
